version: '3.9'
services:
  react-app:
    build: ./
    container_name: mailgroup-viewer-react-app
    volumes:
      - ./app/:/workspaces/app/
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: sh -c "cd /workspaces/app  && npm install &&npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
